// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://weyglmjnikfwszxvplgb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndleWdsbWpuaWtmd3N6eHZwbGdiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQ5ODQ5MzksImV4cCI6MjA1MDU2MDkzOX0.g327moqd4ct-fDObZsySrCiY-90HfMe3-Zk1FNmM75Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);